# Generated by Django 3.0.8 on 2020-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
