# Generated by Django 3.0.8 on 2020-11-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_category_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='view_count',
            field=models.IntegerField(default=None),
        ),
    ]
