# Generated by Django 3.0.8 on 2020-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
